version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ./entrypoint.sh
volumes:
  horilla-data:
