services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:8000
    networks:
      - app_network
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
    command: ./entrypoint.sh
    volumes:
      - horilla-vol:/app
networks:
  app_network:
    external: true
    name: app_network
volumes:
  horilla-vol:
